### ISSUE TITLE
Presentacion

### ISSUE THREAD

**Issue by samusolo** [samusolo/iDoctor#32]
Hay que ver cómo hacemos lo de ponerle un archivo en la presentacion y que al clickar sobre él le abra al archivo indicado.
He podido hacerlo pero como el archivo lleva la ruta de mi ordenador, por ejemplo, no funcionaria en el suyo o en el otro. Se os ocurre algo?

**Comment by esu23** [comment]
Si metemos las cosas en una carpeta y lo enlazamos creo que debería ir en cualquier ordenador con esa misma ruta.

Por ejemplo, suponemos que hacemos una carpeta SRS y dentro de esa carpeta está el video.mp4 y el srs.ptxt o como sea la extension de las diapositivas. Si enlazas desde la diapositiva el archvio video.mp4 debería ir bien porque se conserva la misma ruta aunque lo metas en otro ordenador con un USB por ejemplo. De todas formas no puedo comprobarlo porque desde que me bajé el Visio este el resto del Office (Word, Powerpoint, etc) se me ha desinstalao jajaja.

**Comment by samusolo** [comment]
Yo puedo comprobarlo en los ordenadores de mi casa. Igualmente, si intento meter el video o un archivo dentro de la carpeta "Entrega IS" por ejemplo, seguiría buscando el archivo en mi pc como C:\Samu\Escritorio\EntregaIS\... por poner un ejemplo. Lo suyo sería que acabemos todo, lo metamos ya en carpetas como si fuera la entrega y ya luego vamos probando eso

**Comment by esu23** [comment]
¿Has visto si rula? Yo recuerdo alguna presentación en secundaria que tuve ese problema pero me acabó funcionando. Lo que no me acuerdo como se hacía.

**Comment by agusjm** [comment]
He metido el SRS final pero falta revisarlo , y las tarjetas a ver que os parece

**Comment by agusjm** [comment]
subir los archivos a una carpeta de drive , y poner ese enlace

**Comment by samusolo** [comment]
Sí que funciona, lo único es que tengamos todo en la misma carpeta, así que cuando tengamos todas las carpetas hechas metemos los archivos en las presentaciones y probamos
